cbvdj/urls.py
from django.contrib import admin
from myapp import views
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('myapp/',include('myapp.urls')),
]

myapp/urls.py
from myapp import views
from django.urls import path

app_name = 'myapp'

urlpatterns = [

       path('',views.firstpage,name='page'),
       path('create/',views.PatientCreateView.as_view(),name='create'),
       path('list/',views.PatientListView.as_view(),name='list'),
       path('detail/<int:pk>/',views.PatientDetailView.as_view(),name='detail')
    

]

myapp/models.py
from django.db import models

# Create your models here.

class Patient(models.Model):

    name = models.CharField(max_length=30)
    age = models.IntegerField()
    hospital_name = models.CharField(max_length=30)
    info = models.CharField(max_length=250)

    def __str__(self):

        return f'{self.name} is {self.age} old admitted to {self.hospital_name}'

myapp/forms.py
from django import forms
from myapp.models import Patient


class PatientForm(forms.ModelForm):

    info = forms.CharField(widget=forms.Textarea())

    class Meta():
        model = Patient
        fields = '__all__'

myapp/views.py
from django.shortcuts import render
from django.views.generic import CreateView,ListView,UpdateView,DeleteView,DetailView
from myapp.models import Patient
from myapp.forms import PatientForm
from django.http import HttpResponseRedirect
from django.urls import reverse,reverse_lazy

# Create your views here.

def index(request):
    return render(request,'index.html')

def firstpage(request):

    return render(request,'myapp/page.html')

class PatientCreateView(CreateView):

    model = Patient
    fields = '__all__'
    success_url = reverse_lazy('myapp:list')

class PatientListView(ListView):

    model = Patient
    context_object_name = 'tags'

class PatientDetailView(DetailView):

    model = Patient
    context_object_name = 'tags2'

myapp/templates/myapp/page.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>forst page</h1>
</body>
</html>

myapp/templates/myapp/patient_detaiil.html
{% extends 'base.html'%}

{% block content %}
{{patient}}
{% endblock %}

myapp/templates/myapp/patient_form.html
{% extends 'base.html'%}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="SUBMIT">
</form>

{% endblock %}

myapp/templates/myapp/patient_list.html
{% extends 'base.html'%}

{% block content %}
{% for tag in tags %}
<ul>
<li>{{tag}}</li>
<li><a href="myapp/detail/{{tag.id}}"> {{tag.name}} detail</a></li>
</ul>



{% endfor %}

{% endblock %}

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
              <a class="nav-link" href="{% url 'myapp:create' %}">CREATE</a>
              <a class="nav-link" href="{% url 'myapp:list' %}">LIST</a>
              <a class="nav-link disabled">UPDATE</a>
              <a class="nav-link disabled">DELETE</a>
            </div>
          </div>
        </div>
      </nav> 
</body>
<div class="container"> 
    {% block content %}
    {% endblock %}
</div>
</html>

templates/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>This is index page
    
    </h1>
</body>
</html>